name: 'Collect directories by contained files'
description: 'Returns an array of directories that contain file(s) matching a glob pattern'
branding:
  icon: 'folder'
  color: 'blue'
inputs:
  files-glob:
    description: 'A glob representing the file(s) to search for'
    required: true
  search-directory:
    description: 'The directory to search (if not set, the root directory is used)'
    required: false
    default: '/'
  unique:
    description: 'Whether to return unique values when duplicates may be possible'
    required: false
    default: "true"
outputs:
  directories:
    description: 'An array of parent directories that contain the specified file(s)'
runs:
  using: 'node16'
  main: 'index.js'